USE PhysicianFeb05;

DROP TABLE IF EXISTS PATIENT_TREATMENT;
DROP TABLE IF EXISTS TREATMENT;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS PHYSICIAN;


CREATE TABLE PHYSICIAN (
    Physician_ID INT CONSTRAINT Phy_PK PRIMARY KEY,
    Physician_Name VARCHAR(50)
);


CREATE TABLE PATIENT (
    Patient_ID INT CONSTRAINT Pat_PK PRIMARY KEY,
    Patient_Name VARCHAR(50)
);


CREATE TABLE TREATMENT (
    Treatment_Code INT CONSTRAINT Tra_PK PRIMARY KEY,
    Description VARCHAR(100)
);

CREATE TABLE PATIENT_TREATMENT (
    Physician_ID INT NOT NULL,
    Patient_ID INT NOT NULL,
    Treatment_Code INT NOT NULL,
    Treatment_Date DATE DEFAULT (GETDATE()),
    Treatment_Time TIME DEFAULT (CAST(GETDATE() AS TIME)),
    Results VARCHAR(50),

    CONSTRAINT Phy_FK FOREIGN KEY (Physician_ID) REFERENCES PHYSICIAN (Physician_ID),
    CONSTRAINT Pat_FK FOREIGN KEY (Patient_ID) REFERENCES PATIENT (Patient_ID),
    CONSTRAINT Tra_FK FOREIGN KEY (Treatment_Code) REFERENCES TREATMENT (Treatment_Code)
);

alter table PATIENT_TREATMENT
ADD CONSTRAINT PK_Patient_Treatment PRIMARY KEY (Physician_ID, Patient_ID, Treatment_Code, Treatment_Date)

SELECT * FROM PHYSICIAN;
SELECT * FROM PATIENT;
SELECT * FROM PATIENT_TREATMENT;
SELECT * FROM TREATMENT;


insert into 